Escriba código Python que cree una nueva tupla m1, a partir de la siguiente tupla m, cambiando el nombre de la mascota 'Filis' por 'Firulais'.

Use el operador de corte (slicing) y use concatenación.

m = (‘Filis’,perro,5,10-01-17)

In [29]:
M1=('Filis','perro',5,'10-01-17')
newName ='Firulais'
M1 = (newName,) + M[1:]

print(M1)

('Firulais', 'perro', 5, '10-01-17')


¿Cuál es el resultado de la siguiente operación de tuplas?

aTuple = (100, 200, 300, 400, 500)
aTuple.pop(2)
print(aTuple)

In [6]:

aTuple = (100, 200, 300, 400, 500)
aTuple.pop(2)
print(aTuple)

AttributeError: 'tuple' object has no attribute 'pop'

¿Cuál es el resultado del siguiente código?

set1 = {10, 20, 30, 40, 50}
set2 = {60, 70, 10, 30, 40, 80, 20, 50} 

print(set1.issubset(set2))
print(set2.issuperset(set1))

In [7]:
set1 = {10, 20, 30, 40, 50}
set2 = {60, 70, 10, 30, 40, 80, 20, 50} 

print(set1.issubset(set2))
print(set2.issuperset(set1))

True
True


¿Cuál es el resultado del siguiente código?

sampleSet = {'Amarillo', 'Naranja', 'Negro'}

print(sampleSet[1])

In [8]:

sampleSet = {'Amarillo', 'Naranja', 'Negro'}

print(sampleSet[1])

TypeError: 'set' object is not subscriptable

Selecciona todas las opciones correctas para vaciar el siguiente diccionario

In [14]:
estudiante = {
    "nombre": "Emma",
    "clase" : 9,
    "marks": 75
}

estudiante.clear()

estudiante

{}

Selecciona la manera correcta para acceder el valor de "historia"

In [20]:
SampleDict = {
    "clase": {
        "estudiante":{
            "nombre":"Mike", 
            "marks": {
                "fisica": 70,
                "historia":80
            }
        }
    }
}


SampleDict['clase']['estudiante']['marks']['historia']

80

Escriba un código en Python que le permita crear una lista, uando listas por comprensión, de todas las consonantes en el string "Yellow Yaks like yelling and yawning and yesterday they yodled while eating yuky yams"

In [23]:
frase = "Yellow Yaks like yelling and yawning and yesterday they yodled while eating yuky yams"
consonantes = [ x for x in frase if( x != 'a' and x != 'e' and x != 'i' and x != 'o' and x != 'u')]

consonantes

['Y',
 'l',
 'l',
 'w',
 ' ',
 'Y',
 'k',
 's',
 ' ',
 'l',
 'k',
 ' ',
 'y',
 'l',
 'l',
 'n',
 'g',
 ' ',
 'n',
 'd',
 ' ',
 'y',
 'w',
 'n',
 'n',
 'g',
 ' ',
 'n',
 'd',
 ' ',
 'y',
 's',
 't',
 'r',
 'd',
 'y',
 ' ',
 't',
 'h',
 'y',
 ' ',
 'y',
 'd',
 'l',
 'd',
 ' ',
 'w',
 'h',
 'l',
 ' ',
 't',
 'n',
 'g',
 ' ',
 'y',
 'k',
 'y',
 ' ',
 'y',
 'm',
 's']

Escriba un código en Python que le permita obtener el índice y el valor como tupla para ítems en una lista.

Use la lista

items = ["hi", 4, 8.99, 'apple', ('t,b','n')] para hacer una prueba de su código.

El resultado (salida del código) debe verse así:

[(0, 'hi'), (1, 4), (2, 8.99), (3, 'apple'), (4, ('t,b', 'n'))]

In [68]:
items = ["hi", 4, 8.99, 'apple', ('t,b','n')]

result = []
for i in range(len(items)):
    result.append((i, items[i]))

print(result)


[(0, 'hi'), (1, 4), (2, 8.99), (3, 'apple'), (4, ('t,b', 'n'))]


Complete el siguiente código Python que reorganice positivos, ceros y negativos en una lista usando una función lambda. Primero se mostrarán los positivos ascendentemente, luego los ceros y finalmente los negativos ascendentemente.  Debe usar la función sorted(iterable, /, *, key=None, reverse=False), misma que devuelve una nueva lista que contiene todos los elementos del iterable en orden ascendente (reverse=True se usa para orden descendente y key se usa para especificar la función que personaliza el orden). Se sugiere usar una función para los elementos diferentes de cero en la que se invierta el elemento x (1/x) y se multiplique por -1 y en caso de cero se use el propio cero.

In [ ]:
nums = [-1, 2, -3, 0, 5, 7, 8, 9, -10, 0]

print("Lista original:")
print(nums)

result = sorted(nums, key=lambda x: (x>0)*x + (x==0)*float('inf') + (x<0)*(1/x))

print("\nReorganizados:")
print(result)


Complete el siguiente código Python que calcula el cuadrado y el cubo todos los números de la siguiente lista de enteros usando funciones lambda.

In [56]:
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 
print("Lista original:") 
print(nums) 
print("\nLista al cuadrado:") 
square_nums = (list(map(lambda x: x ** 2 , nums)))


print(square_nums) 
print("\nLista al cubo:") 
cube_nums = (list(map(lambda x: x ** 3 , nums)))

 
print(cube_nums)

Lista original:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Lista al cuadrado:
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

Lista al cubo:
[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]


Escribe una función generadora que produzca una contraseña al azar que cumpla con las siguientes condiciones. Se sugiere importar el módulo string para usar sus facilidades, así como el módulo random.

La contraseña debe contar de 10 caracteres
Debe tener como mínimo 2 mayúsculas, 1 dígito y 1 símbolo especial

In [79]:
import string
import random

def generar_contrasena():
    longitud = 10
    caracteres = string.ascii_letters + string.digits + string.punctuation
    while True:
        contrasena = ''.join(random.choice(caracteres) for i in range(longitud))
        if (sum(1 for c in contrasena if c.isupper()) >= 2
                and sum(1 for c in contrasena if c.isdigit()) >= 1
                and sum(1 for c in contrasena if c in string.punctuation) >= 1):
            break
    return contrasena


Complete la función imp_lineas(arch,subcad) a la que se le pasa un nombre de archivo (incluida su ruta) y una cadena e imprima solo las líneas del archivo que contengan la cadena. Dicha función debe llamar a la siguiente función generadora:

def readfiles(filenames):   
    ''' filenames: lista de nombres de archivos con su ruta'''
    for f in filenames:
        for line in open(f):
            yield line
 

def imp_lineas(arch,subcad):
    '''
    Parameters
    ----------
    arch : list
        lista de nombres de archivos
    subcad : str
        cadena de caracteres presente en la línea a imprimir.
    '''

    .....

In [59]:
def imp_lineas(list_arch,subcadena):
    for line in readfiles(list_arch):
        if( line.find(subcadena)):
            print(line)

imprimelos a enteros 
arr1 = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])

In [67]:
import numpy as np
arr1 = np.array([[2.5, 3.8, 1.5],[4.7, 2.9, 1.56]])
print(arr1.astype(int))




[[2 3 1]
 [4 2 1]]


In [72]:
import numpy as np

a1 = np.array([[1,2,3],
               [4,5,6]])
a2 = np.array([[7,8,9],
               [10,11,12]])

print(np.vstack((a1, a2)))



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [78]:
import numpy as np

arr1 = np.array([1, 2, 3, 5])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
Array.from(new Set(myArray1.concat(myArray2))); 

print(unique)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 