In [6]:
import numpy as np

Escribe un programa Python usando numpy para invertir un arreglo (el primer elemento se convierte en el último)

La salida del código debe verse así:

Arreglo original:

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

Arreglo invertido:

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [7]:
a= np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37])

a = a[::-1]
a

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

Escribe un programa Python usando numpy que convierta cualquier arreglo con un tipo compatible a tipo flotante.

La salida debe verse así:

Arreglo original: [1, 2, 3, 4]

Arreglo convertido a flotante: [ 1. 2. 3. 4.]










In [8]:
b= np.array([1, 2, 3,4],dtype=float)

b

array([1., 2., 3., 4.])

Escribe un programa Python usando numpy para convertir una lista a arreglo y una tupla a arreglo. Note el problema de forma en ambos casos.

Si las entradas fueran:

 Lista : [[1, 2, 3], [4, 5, 6, 7, 8]]

Tupla: ([8, 4], [1, 2, 3])

In [10]:
Lista = [[1, 2, 3], [4, 5, 6, 7, 8]]

Tupla =  ([8, 4], [1, 2, 3])
np.asarray(Lista)

np.asarray(Tupla)

C:\Users\david\AppData\Local\Temp\ipykernel_18532\3479344271.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.asarray(Lista)
C:\Users\david\AppData\Local\Temp\ipykernel_18532\3479344271.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.asarray(Tupla)


array([list([8, 4]), list([1, 2, 3])], dtype=object)

Escribe un programa Python usando numpy.append() para añadir valores al final de un arreglo.

Las salidas del código deben verse así:

Arreglo original: [10, 20, 30]

Arreglo tras añadir valores: [10 20 30 40 50 60 70 80 90]

In [19]:
ArregloOriginal= np.array([10, 20, 30])

arrNuevosValores =np.array([40,50,60,70,80,90])

ArregloOriginal = np.append(ArregloOriginal,arrNuevosValores) 

print(ArregloOriginal)



[10 20 30 40 50 60 70 80 90]


Escribe un programa Python usando numpy para encontrar la unión de dos arreglos. La unión regresará los valores únicos en cualquiera de los dos arreglos de manera ordenada

Las salidas del código deben verse así:

array 1: [ 0 10 20 40 60 80]

array 2: [10 30 40 50 70]

Valores únicos en ambos arreglos de manera ordenada: 

[ 0 10 20 30 40 50 60 70 80]

In [22]:
array1 = np.array([0,10,20,40,60,80])

array2 = np.array([10,30,40,50,70])

arr =  np.append(array1,array2)

arr = np.unique(arr)

arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

Escribe un programa Python usando numpy para crear un arreglo con valores de 12 a 38

La salida al imprimir el arreglo debe verse así:

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

In [26]:
d = np.arange(12,38)
print(d)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


Complete el siguiente código Python, usando numpy, para encontrar los valores comunes entre dos arreglos.

import numpy as np 
array1 = np.array([0, 10, 20, 40, 60]) 
print("Array1: ",array1) 
array2 = [0, 40] 
print("Array2: ",array2) 
print("Compara cada elemento del array 1 y array 2") 
______________
Las salida deben verse así:

[ True False False True False]

In [39]:

arr1 = np.array([0, 10, 20, 40, 60]) 
print("Array1: ",array1) 
arr2 = [0, 40] 
print("Array2: ",array2) 
print("Compara cada elemento del array 1 y array 2") 

print(np.equal(arr1,arr2))


Array1:  [ 0 10 20 40 60]
Array2:  [0, 40]
Compara cada elemento del array 1 y array 2


ValueError: operands could not be broadcast together with shapes (5,) (2,) 

Escriba código Python usando numpy para encontrar la unión entre dos arreglos. La unión mostrará datos que se encuentren en ambos arreglos.

Las salidas del código deben verse así:


array1: [ 0 10 20 40 60 80]
array2: [10, 30, 40, 50, 70]
Valores que se encuentran en los arreglos:
[ 0 10 20 30 40 50 60 70 80]

In [36]:
array1 = np.array([0,10,20,40,60,80])

array2 = np.array([10,30,40,50,70])

arr =  np.append(array1,array2)

arr = np.unique(arr)

print(arr)


[ 0 10 20 30 40 50 60 70 80]
