¿Cuál de los siguientes enunciados es verdad sobre los diccionarios en Python?

-Se accede a los diccionarios con keys: Verdadero, los diccionarios se acceden mediante la clave correspondiente a cada valor.

-Los diccionarios son mutables: Verdadero, los diccionarios son estructuras de datos mutables, lo que significa que se pueden modificar agregando, eliminando o actualizando elementos.

-Los diccionarios pueden ser anidados a cualquier profundidad: Verdadero, los diccionarios pueden contener cualquier tipo de objeto, incluidos otros diccionarios, lo que permite anidarlos a cualquier profundidad.


Escriba un código en Python, usando comprensión de listas, que le permita encontrar todos los números entre 1 y 1000 (inclusivos) que sean divisibles entre 7


In [1]:
divSiete = [num for num in range(1,1000+1) if num % 7  == 0 ]
print(divSiete)

[7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98, 105, 112, 119, 126, 133, 140, 147, 154, 161, 168, 175, 182, 189, 196, 203, 210, 217, 224, 231, 238, 245, 252, 259, 266, 273, 280, 287, 294, 301, 308, 315, 322, 329, 336, 343, 350, 357, 364, 371, 378, 385, 392, 399, 406, 413, 420, 427, 434, 441, 448, 455, 462, 469, 476, 483, 490, 497, 504, 511, 518, 525, 532, 539, 546, 553, 560, 567, 574, 581, 588, 595, 602, 609, 616, 623, 630, 637, 644, 651, 658, 665, 672, 679, 686, 693, 700, 707, 714, 721, 728, 735, 742, 749, 756, 763, 770, 777, 784, 791, 798, 805, 812, 819, 826, 833, 840, 847, 854, 861, 868, 875, 882, 889, 896, 903, 910, 917, 924, 931, 938, 945, 952, 959, 966, 973, 980, 987, 994]


Escriba un código en Python con lista por comprensión que permita contar el número de espacios en un string e imprima la cantidad total de espacios.

In [2]:
palabra = "asd as as ads   asd"
listaEspacio = [letra for letra in "asd as as ads   asd" if letra  == " " ]
print(listaEspacio)

[' ', ' ', ' ', ' ', ' ', ' ']


Escribe un código Python, usando listas por comprensión, que permita encontrar palabras en un string que contengan menos de 4 letras.

In [6]:
palabra = "asd   asdws  sssas as ads   asd sdasdsas"
palabraEspacio = [word for word in palabra.split() if len(word) < 4]
print(palabraEspacio)



['asd', 'as', 'ads', 'asd']


Complete el siguiente código Python, de manera que extraiga año, mes y día usando función lambda

In [16]:
import datetime 
now = datetime.datetime.now() 
print(now) 


year = lambda date: date.year

 
month = lambda date: date.month

 
day = lambda date: date.day

 
t = lambda date: date.strftime("%H:%M:%S.%f")

 
print(year(now)) 
print(month(now)) 
print(day(now)) 
print(t(now))

#https://www.w3schools.com/python/python_lambda.asp#:~:text=A%20lambda%20function%20is%20a,can%20only%20have%20one%20expression.
#https://www.w3schools.com/python/python_datetime.asp

2023-03-21 10:18:20.021151
2023
3
21
10:18:20.021151


Escribe un programa Python para filtrar una lista de enteros usando lambda

El resultado debe verse así:

Lista original: [1,2,3,4,5,6,7,8,9,10]

Números pares de la lista: [2,4,6,8,10]

Números impares de la lista: [1,3,5,7,9]

In [9]:
original=[1,2,3,4,5,6,7,8,9,10]
pares = []
impares = []

separadorPares = list(filter(lambda x : x % 2 == 0, original))
separadorImpares = list(filter(lambda x : x % 2 != 0, original))

print("Lista original:" + str(original[0:]))

print("Números pares de la lista:"+ str(separadorPares[0:]))
print("Números impares de la lista: "+ str(separadorImpares[0:]))


Lista original:[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Números pares de la lista:[2, 4, 6, 8, 10]
Números impares de la lista: [1, 3, 5, 7, 9]


Escriba una función imp_lineas(list_arch) que, dada una lista de nombres de archivos, imprima cada una de sus líneas. La función debe usar la siguiente función generadora:

def readfiles(filenames):
    ''' filenames: lista de nombres de archivos con su ruta'''
    for f in filenames:
        for line in open(f):
            yield line

In [ ]:
def imp_lineas(list_arch,subcadena):
    for line in readfiles(list_arch):
        if(line)
print(line)


Escribe una función findfiles(directorio) que descienda repetidamente la estructura por el directorio especificado y genere caminos para todos los archivos en la estructura, y que use la siguiente función generadora:

def readfiles(filenames):
    ''' filenames: lista de nombres de archivos con su ruta''' 
    for f in filenames: 
        for line in open(f): 
            yield line

In [ ]:
import os

def findfiles(directorio):
    for root, dirs, files in os.walk(directorio):
        for name in files:
            yield os.path.join(root, name)

Escriba un código Python usando numpy para obtener los valores e indices de los elementos que sean mayores a 10 en un arreglo x.

TIP: np.nonzero(a) Retorna los índices de los elementos que no son cero

La salida debe verse así:

Arreglo original:
[[ 0 10 20]
[20 30 40]]
Valores mayores a 10 = [20 20 30 40]
Sus índices en el arreglo original son:

Posición por filas: [0, 1, 1, 1])

Posición por columnas: [2, 0, 1, 2]

In [11]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])

mayores_a_10 = x[x > 10]

indices = np.nonzero(x > 10)

print("Arreglo original:\n", x)
print("Valores mayores a 10 =", mayores_a_10)
print("Sus índices en el arreglo original son:")
print("Posición por filas:", indices[0])
print("Posición por columnas:", indices[1])

Arreglo original:
 [[ 0 10 20]
 [20 30 40]]
Valores mayores a 10 = [20 20 30 40]
Sus índices en el arreglo original son:
Posición por filas: [0 1 1 1]
Posición por columnas: [2 0 1 2]


Escribe un programa Python usando numpy para encontrar la unión de dos arreglos. La unión regresará los valores únicos en cualquiera de los dos arreglos de manera ordenada

Las salidas del código deben verse así:

array 1: [ 0 10 20 40 60 80]

array 2: [10 30 40 50 70]

Valores únicos en ambos arreglos de manera ordenada: 

[ 0 10 20 30 40 50 60 70 80]

In [12]:
import numpy as np

array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])

union = np.union1d(array1, array2)

print("array 1:", array1)
print("array 2:", array2)
print("Valores únicos en ambos arreglos de manera ordenada:\n", union)


array 1: [ 0 10 20 40 60 80]
array 2: [10 30 40 50 70]
Valores únicos en ambos arreglos de manera ordenada:
 [ 0 10 20 30 40 50 60 70 80]


Completa el siguiente programa en Python, usando numpy para convertir una lista a arreglo y una tupla a arreglo.

import numpy as np
my_list = [[1, 2, 3], [5, 6, 7, 8]]
print("De lista a arreglo: ")
print(np.asarray(
 ))
my_tuple = ([8, 4], [1, 2, 3])
print("De tupla a arreglo: ")
print(np.asarray(
 ))

 

In [13]:
import numpy as np
my_list = [[1, 2, 3], [5, 6, 7, 8]]

print("De lista a arreglo: ")

print(np.asarray( my_list ))

my_tuple = ([8, 4], [1, 2, 3])

print("De tupla a arreglo: ")
print(np.asarray(my_tuple))

 

De lista a arreglo: 
[list([1, 2, 3]) list([5, 6, 7, 8])]
De tupla a arreglo: 
[list([8, 4]) list([1, 2, 3])]


C:\Users\david\AppData\Local\Temp\ipykernel_2680\319627498.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print(np.asarray( my_list ))
C:\Users\david\AppData\Local\Temp\ipykernel_2680\319627498.py:8: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print(np.asarray(my_tuple))


Complete el siguiente programa en Python usando numpy para invertir un arreglo (el primer elemento se convierte en el último)

La salida del código debe verse así:

Arreglo original:

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

Arreglo invertido:

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

 

import numpy as np
x = np.arange(12, 38)
print("Arreglo original:")
print(x)
print("Arreglo invertido:")
______________
print(x)

In [17]:
import numpy as np
x = np.arange(12, 38)
print("Arreglo original:")
print(x)
print("Arreglo invertido:")
x= np.flip(x)
print(x)

Arreglo original:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Arreglo invertido:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]
